  include: package:pedantic/analysis_options.yaml

  analyzer:
  exclude: [build/**]
  strong-mode:
    implicit-casts: false

  linter:
    rules:
      - annotate_overrides
      - await_only_futures
      - camel_case_types
      - cancel_subscriptions
      - close_sinks
      - comment_references
      - constant_identifier_names
      - control_flow_in_finally
      - empty_statements
      - avoid_empty_else